import PDFDocument from 'pdfkit';
import { log } from '../utils/logger.js';
import { getDb } from '../db/connection.js';

const MODULE = 'reportService';

const DARK_BLUE  = '#0d2b5e';
const MID_BLUE   = '#1a3a6b';
const LIGHT_BLUE = '#dce8f8';
const GREEN      = '#155a15';
const GREEN_BG   = '#eaf5ea';
const RED        = '#8b0000';
const RED_BG     = '#fdecea';
const GREY_DARK  = '#222222';
const GREY_MID   = '#555555';
const GREY_LIGHT = '#888888';
const STRIPE_A   = '#f4f7fb';
const STRIPE_B   = '#ffffff';

const PAGE_W   = 595;
const PAGE_H   = 841;
const MARGIN   = 50;
const USABLE_W = PAGE_W - MARGIN * 2;  // 495
// Keep content above this y so the footer has room
const SAFE_Y   = PAGE_H - MARGIN - 35; // ~756

function trunc(s, max = 44) {
  if (!s) return '';
  return s.length > max ? s.slice(0, max - 1) + '…' : s;
}

/**
 * Draw the footer at the bottom of the CURRENT page.
 * Call this just BEFORE doc.addPage() so doc.y is not affected for the next page.
 */
function drawFooter(doc) {
  const fy = PAGE_H - MARGIN;
  doc.moveTo(MARGIN, fy - 14)
    .lineTo(MARGIN + USABLE_W, fy - 14)
    .strokeColor('#cccccc').lineWidth(0.5).stroke();
  doc.fillColor(GREY_LIGHT).fontSize(7).font('Helvetica')
    .text(
      'This report is generated by Credit Path AI and is intended for official academic review purposes only.',
      MARGIN, fy - 10, { align: 'center', width: USABLE_W, lineBreak: false }
    );
  // NOTE: we do NOT reset doc.y here — caller must call doc.addPage() next,
  // which automatically resets doc.y to the top margin.
}

/**
 * Finalize the current page (draw footer) then start a new one.
 * Returns the starting y for content on the new page.
 */
function nextPage(doc) {
  drawFooter(doc);
  doc.addPage();
  return MARGIN + 10;
}

/**
 * If y + needed would exceed the safe area, start a new page.
 */
function ensureSpace(doc, y, needed) {
  if (y + needed > SAFE_Y) return nextPage(doc);
  return y;
}

/** Blue section heading with rule. Returns new y. */
function heading(doc, label, y) {
  doc.fillColor(MID_BLUE).fontSize(12).font('Helvetica-Bold')
    .text(label, MARGIN, y, { lineBreak: false });
  y += 17;
  doc.moveTo(MARGIN, y).lineTo(MARGIN + USABLE_W, y)
    .strokeColor(MID_BLUE).lineWidth(0.8).stroke();
  return y + 8;
}

/** Two-value info row (label | value). Returns new y after the row. */
function infoRow(doc, label, value, y) {
  const LABEL_X = MARGIN + 4;
  const LABEL_W = 155;
  const VALUE_X = LABEL_X + LABEL_W + 6;
  const VALUE_W = USABLE_W - 4 - LABEL_W - 6;

  doc.font('Helvetica-Bold').fillColor(GREY_DARK).fontSize(9.5)
    .text(label + ':', LABEL_X, y, { width: LABEL_W, lineBreak: false });
  doc.font('Helvetica').fillColor(GREY_MID)
    .text(value, VALUE_X, y, { width: VALUE_W });
  // Use doc.y (which reflects actual wrapped height) + padding
  return doc.y + 5;
}

// ─────────────────────────────────────────────────────────────────────────────

export async function generateReport({ analysisId, res }) {
  const fn = 'generateReport';
  log.info({ module: MODULE, fn, analysisId }, 'Generating PDF report');

  try {
    const db = getDb();

    const analysis = db.prepare('SELECT * FROM analyses WHERE id = ?').get(analysisId);
    if (!analysis) throw new Error(`Analysis not found: ${analysisId}`);

    const user = db.prepare(
      `SELECT u.name, s.reg_no, s.ic_no, s.diploma_institution, s.diploma_programme, s.cgpa
       FROM users u LEFT JOIN students s ON s.user_id = u.id WHERE u.id = ?`
    ).get(analysis.student_id);

    const prog       = db.prepare('SELECT * FROM uni_programmes WHERE id = ?').get(analysis.target_programme_id);
    const strategies = analysis.strategies_json ? JSON.parse(analysis.strategies_json) : null;
    const result     = analysis.result_json     ? JSON.parse(analysis.result_json)     : null;
    const verdicts   = result?.llmVerdicts || [];

    const doc = new PDFDocument({ margin: MARGIN, size: 'A4', autoFirstPage: true });
    res.setHeader('Content-Type', 'application/pdf');
    res.setHeader('Content-Disposition',
      `attachment; filename="credit-transfer-report-${analysisId.slice(0, 8)}.pdf"`);
    doc.pipe(res);

    // ══════════════════════════════════════════════════════════════════════════
    // PAGE 1 — STUDENT INFORMATION
    // ══════════════════════════════════════════════════════════════════════════
    doc.rect(0, 0, PAGE_W, 108).fill(DARK_BLUE);
    doc.fillColor('white').fontSize(17).font('Helvetica-Bold')
      .text('CREDIT TRANSFER ANALYSIS REPORT', MARGIN, 28, { lineBreak: false });
    doc.fontSize(10).font('Helvetica')
      .text('Universiti Kebangsaan Malaysia  —  Fakulti Teknologi dan Sains Maklumat', MARGIN, 56, { lineBreak: false })
      .text('Report Date: ' + new Date().toLocaleDateString('en-MY', { year: 'numeric', month: 'long', day: 'numeric' }), MARGIN, 71, { lineBreak: false })
      .text('Reference: ' + analysisId, MARGIN, 86, { lineBreak: false });

    let y = 126;
    y = heading(doc, 'STUDENT INFORMATION', y);

    const infoRows = [
      ['Student Name',          user?.name               || '—'],
      ['Registration Number',   user?.reg_no              || '—'],
      ['Identity Card No.',     user?.ic_no               || '—'],
      ['Diploma Institution',   user?.diploma_institution || '—'],
      ['Diploma Programme',     user?.diploma_programme   || '—'],
      ['Cumulative GPA',        user?.cgpa != null ? user.cgpa.toFixed(2) : '—'],
      ['Target UKM Programme',  prog ? `${prog.name}  (${prog.code})` : '—'],
      ['Date of Analysis',      new Date(analysis.created_at).toLocaleDateString('en-MY', { day: '2-digit', month: 'long', year: 'numeric' })],
    ];

    for (const [label, val] of infoRows) {
      y = infoRow(doc, label, val, y);
    }

    // ══════════════════════════════════════════════════════════════════════════
    // PAGES 2+ — SUBJECT TOPIC ANALYSIS
    // ══════════════════════════════════════════════════════════════════════════
    if (verdicts.length > 0) {
      y = nextPage(doc);
      y = heading(doc, 'SUBJECT TOPIC ANALYSIS', y);

      doc.fillColor(GREY_MID).fontSize(9).font('Helvetica')
        .text(
          'The following tables present a detailed topic-by-topic analysis for each subject included ' +
          'in the credit transfer request. Topics marked "Matched" indicate content covered by the ' +
          'diploma syllabus. "Unmatched" topics represent gaps that may require additional assessment.',
          MARGIN, y, { width: USABLE_W }
        );
      y = doc.y + 14;

      for (const [vi, verd] of verdicts.entries()) {
        const uniCode  = verd.uniCode    || verd.uni_code    || '';
        const dipCodes = verd.diplomaCodes || verd.diploma_codes || [];
        const matched   = verd.matched   || [];
        const unmatched = verd.unmatched || [];
        const coverage  = verd.final_coverage_percent ?? verd.coverage_percent ?? verd.coverage ?? 0;
        const verdict   = verd.verdict || 'pending';
        const reason    = verd.reason  || '';

        const uniSubj  = db.prepare('SELECT name, credit FROM uni_subjects WHERE code = ?').get(uniCode);
        const dipSubjs = dipCodes.map(c =>
          db.prepare('SELECT name, institution FROM diploma_subjects WHERE code = ?').get(c)
        );

        const totalTopics = matched.length + unmatched.length;
        // Estimate block height: header + info bar + dipCode rows + table header + rows + note
        const estH = 28 + 16 + Math.max(dipCodes.length, 1) * 15 + 14 + 17 +
                     (totalTopics || 1) * 14 + (reason ? 30 : 0) + 20;
        y = ensureSpace(doc, y, estH);

        const verdColor = verdict.includes('approved') ? GREEN : verdict === 'rejected' ? RED : '#7a5c00';
        const verdBg    = verdict.includes('approved') ? GREEN_BG : verdict === 'rejected' ? RED_BG : '#fdf6e3';

        // Subject header bar
        doc.rect(MARGIN, y, USABLE_W, 26).fill(verdBg);
        doc.fillColor(verdColor).fontSize(10).font('Helvetica-Bold')
          .text(
            `${vi + 1}.   ${uniCode}${uniSubj ? '  —  ' + uniSubj.name : ''}`,
            MARGIN + 8, y + 8, { width: USABLE_W - 110, lineBreak: false }
          );

        // Verdict badge (right side of header bar)
        const BADGE_W   = 90;
        const BADGE_LABEL = verdict.includes('approved') ? 'PASS'
                          : verdict === 'rejected'       ? 'FAIL'
                          : verdict.replace(/_/g, ' ').toUpperCase();
        doc.roundedRect(MARGIN + USABLE_W - BADGE_W - 6, y + 6, BADGE_W, 14, 3).fill(verdColor);
        doc.fillColor('white').fontSize(7).font('Helvetica-Bold')
          .text(BADGE_LABEL, MARGIN + USABLE_W - BADGE_W - 4, y + 9,
            { width: BADGE_W, align: 'center', lineBreak: false });
        y += 26;

        // Stats row
        doc.rect(MARGIN, y, USABLE_W, 15).fill(STRIPE_A);
        doc.fillColor(GREY_MID).fontSize(8.5).font('Helvetica')
          .text(
            `Credit Hours: ${uniSubj?.credit ?? '—'}   |   Topic Coverage: ${coverage}%   |   Matched: ${matched.length} / ${totalTopics} topics`,
            MARGIN + 8, y + 3, { lineBreak: false }
          );
        y += 15;

        // Diploma source subjects
        y += 4;
        doc.fillColor(GREY_DARK).fontSize(8.5).font('Helvetica-Bold')
          .text('Diploma Source Subject(s):', MARGIN + 8, y);
        y = doc.y + 2;
        for (const [di, code] of dipCodes.entries()) {
          const ds = dipSubjs[di];
          const label = ds
            ? `${code}  —  ${ds.name}  (${trunc(ds.institution || '', 36)})`
            : code;
          doc.fillColor(GREY_MID).fontSize(8.5).font('Helvetica')
            .text('•   ' + label, MARGIN + 20, y, { width: USABLE_W - 28, lineBreak: false });
          y = doc.y + 2;
        }
        y += 6;

        // Build topic → diploma code lookup for per-row attribution
        // Each diploma subject's topics_json tells us which topics it covers.
        // We match uni topic names (case-insensitive + word-overlap fallback) to find the source.
        const topicSourceMap = {};
        for (const code of dipCodes) {
          const dipRow = db.prepare('SELECT topics_json FROM diploma_subjects WHERE code = ?').get(code);
          if (dipRow?.topics_json) {
            try {
              const arr = JSON.parse(dipRow.topics_json);
              for (const t of (Array.isArray(arr) ? arr : [])) {
                const norm = String(t).toLowerCase().trim();
                if (!topicSourceMap[norm]) topicSourceMap[norm] = code;
              }
            } catch { /* ignore */ }
          }
        }
        const getDiplomaSource = (uniTopic) => {
          const key = uniTopic.toLowerCase().trim();
          if (topicSourceMap[key]) return topicSourceMap[key];
          // Word-overlap fallback: any significant word in the uni topic appears in a diploma topic
          const words = key.split(/\s+/).filter(w => w.length > 3);
          for (const [dt, code] of Object.entries(topicSourceMap)) {
            if (words.some(w => dt.includes(w))) return code;
          }
          // Last resort: if only one diploma subject, attribute to it
          return dipCodes.length === 1 ? dipCodes[0] : null;
        };

        // ── Topic mapping table ─────────────────────────────────────────────
        const T_X   = MARGIN + 10;
        const T_W   = USABLE_W - 20;
        const NO_W  = 28;
        const DIP_W = 72;   // diploma code column
        const ST_W  = 72;   // status column
        const TPC_W = T_W - NO_W - DIP_W - ST_W;
        const ROW_H = 14;

        // Table header
        y = ensureSpace(doc, y, 20);
        doc.rect(T_X, y, T_W, 17).fill(MID_BLUE);
        doc.fillColor('white').fontSize(7.5).font('Helvetica-Bold')
          .text('No.',           T_X + 4,                        y + 5, { width: NO_W,         lineBreak: false })
          .text('University Subject Topic (Required)',
                                 T_X + NO_W + 4,                 y + 5, { width: TPC_W - 8,    lineBreak: false })
          .text('Diploma Subject', T_X + NO_W + TPC_W + 4,      y + 5, { width: DIP_W - 4,    lineBreak: false })
          .text('Status',         T_X + NO_W + TPC_W + DIP_W + 4, y + 5, { width: ST_W - 8, lineBreak: false });
        y += 17;

        let rowNum = 1;

        for (const topic of matched) {
          y = ensureSpace(doc, y, ROW_H + 2);
          doc.rect(T_X, y, T_W, ROW_H).fill(rowNum % 2 === 0 ? STRIPE_A : STRIPE_B);
          doc.fillColor(GREY_DARK).fontSize(8).font('Helvetica')
            .text(String(rowNum), T_X + 4, y + 3, { width: NO_W, lineBreak: false });
          doc.fillColor(GREY_DARK)
            .text(trunc(topic, 52), T_X + NO_W + 4, y + 3, { width: TPC_W - 8, lineBreak: false });
          // Per-topic diploma attribution
          const src = getDiplomaSource(topic);
          const dipDisplay = src || trunc(dipCodes.join('+'), 14);
          doc.fillColor(MID_BLUE).fontSize(7.5).font('Helvetica')
            .text(dipDisplay, T_X + NO_W + TPC_W + 4, y + 3, { width: DIP_W - 4, lineBreak: false });
          // Status cell (green)
          doc.rect(T_X + NO_W + TPC_W + DIP_W, y, ST_W, ROW_H).fill(GREEN_BG);
          doc.fillColor(GREEN).fontSize(7.5).font('Helvetica-Bold')
            .text('Matched', T_X + NO_W + TPC_W + DIP_W + 4, y + 3, { width: ST_W - 8, lineBreak: false });
          y += ROW_H;
          rowNum++;
        }

        for (const topic of unmatched) {
          y = ensureSpace(doc, y, ROW_H + 2);
          doc.rect(T_X, y, T_W, ROW_H).fill(rowNum % 2 === 0 ? STRIPE_A : STRIPE_B);
          doc.fillColor(GREY_DARK).fontSize(8).font('Helvetica')
            .text(String(rowNum), T_X + 4, y + 3, { width: NO_W, lineBreak: false });
          doc.fillColor(GREY_DARK)
            .text(trunc(topic, 52), T_X + NO_W + 4, y + 3, { width: TPC_W - 8, lineBreak: false });
          // Diploma code cell — dash for unmatched
          doc.fillColor(GREY_LIGHT).fontSize(7.5).font('Helvetica')
            .text('—', T_X + NO_W + TPC_W + 4, y + 3, { width: DIP_W - 4, lineBreak: false });
          // Status cell (red)
          doc.rect(T_X + NO_W + TPC_W + DIP_W, y, ST_W, ROW_H).fill(RED_BG);
          doc.fillColor(RED).fontSize(7.5).font('Helvetica-Bold')
            .text('Unmatched', T_X + NO_W + TPC_W + DIP_W + 4, y + 3, { width: ST_W - 8, lineBreak: false });
          y += ROW_H;
          rowNum++;
        }

        if (totalTopics === 0) {
          doc.rect(T_X, y, T_W, ROW_H).fill(STRIPE_A);
          doc.fillColor(GREY_LIGHT).fontSize(8).font('Helvetica-Oblique')
            .text('No topic data available.', T_X + NO_W + 4, y + 3, { width: TPC_W - 8, lineBreak: false });
          y += ROW_H;
        }

        // AI assessment note
        if (reason) {
          y = ensureSpace(doc, y, 22);
          doc.rect(T_X, y, T_W, 1).fill('#d0d0d0');
          y += 4;
          doc.fillColor(GREY_MID).fontSize(8).font('Helvetica-Oblique')
            .text('Assessment Note:  ' + reason, T_X, y, { width: T_W });
          y = doc.y + 4;
        }
        y += 18;
      }
    }

    // ══════════════════════════════════════════════════════════════════════════
    // FINAL PAGE — CREDIT TRANSFER SUMMARY
    // ══════════════════════════════════════════════════════════════════════════
    y = nextPage(doc);
    y = heading(doc, 'CREDIT TRANSFER SUMMARY', y);

    doc.fillColor(GREY_MID).fontSize(9).font('Helvetica')
      .text(
        'The table below summarises all subjects included in this credit transfer request, ' +
        'together with the corresponding credit hours and AI assessment outcome.',
        MARGIN, y, { width: USABLE_W }
      );
    y = doc.y + 10;

    // Summary table column widths
    const SC   = [28, 80, 140, 110, 44, 44, 50];
    const SHDRS = ['No.', 'Subject Code', 'Subject Name', 'Diploma Source(s)', 'Credit Hrs', 'Coverage', 'AI Outcome'];
    const S_TBL_W = SC.reduce((a, b) => a + b, 0);

    y = ensureSpace(doc, y, 20);
    doc.rect(MARGIN, y, S_TBL_W, 18).fill(DARK_BLUE);
    let cx = MARGIN + 4;
    doc.fillColor('white').fontSize(7.5).font('Helvetica-Bold');
    for (const [i, h] of SHDRS.entries()) {
      doc.text(h, cx, y + 5, { width: SC[i], lineBreak: false });
      cx += SC[i];
    }
    y += 18;

    let grandTotal   = 0;
    let approvedTotal = 0;

    for (const [vi, verd] of verdicts.entries()) {
      y = ensureSpace(doc, y, 16);
      const uniCode  = verd.uniCode || verd.uni_code || '';
      const dipCodes = verd.diplomaCodes || verd.diploma_codes || [];
      const coverage = verd.final_coverage_percent ?? verd.coverage_percent ?? verd.coverage ?? 0;
      const verdict  = verd.verdict || 'pending';
      const uniSubj  = db.prepare('SELECT name, credit FROM uni_subjects WHERE code = ?').get(uniCode);
      const credits  = uniSubj?.credit ?? 0;

      grandTotal   += credits;
      if (verdict.includes('approved')) approvedTotal += credits;

      const rowBg = verdict.includes('approved')
        ? (vi % 2 === 0 ? '#edf7ed' : '#f5faf5')
        : verdict === 'rejected'
          ? (vi % 2 === 0 ? '#fdf0f0' : '#fef6f6')
          : (vi % 2 === 0 ? STRIPE_A : STRIPE_B);

      doc.rect(MARGIN, y, S_TBL_W, 15).fill(rowBg);
      cx = MARGIN + 4;
      const verdColor = verdict.includes('approved') ? GREEN : verdict === 'rejected' ? RED : '#7a5c00';
      const summCells = [
        String(vi + 1),
        uniCode,
        trunc(uniSubj?.name || '', 26),
        trunc(dipCodes.join(' + '), 22),
        String(credits),
        coverage + '%',
        trunc(verdict.replace(/_/g, ' '), 14),
      ];
      doc.fontSize(8).font('Helvetica');
      for (const [i, cell] of summCells.entries()) {
        doc.fillColor(i === 6 ? verdColor : GREY_DARK)
          .font(i === 6 ? 'Helvetica-Bold' : 'Helvetica')
          .text(cell, cx, y + 3, { width: SC[i], lineBreak: false });
        cx += SC[i];
      }
      y += 15;
    }

    // Totals rows
    y = ensureSpace(doc, y, 38);
    doc.rect(MARGIN, y, S_TBL_W, 17).fill(MID_BLUE);
    doc.fillColor('white').fontSize(8.5).font('Helvetica-Bold')
      .text('TOTAL CREDIT HOURS ASSESSED',
        MARGIN + 4, y + 4, { width: SC[0]+SC[1]+SC[2]+SC[3]-8, lineBreak: false })
      .text(String(grandTotal),
        MARGIN + SC[0]+SC[1]+SC[2]+SC[3] + 4, y + 4, { width: SC[4], lineBreak: false });
    y += 17;

    doc.rect(MARGIN, y, S_TBL_W, 17).fill(GREEN_BG);
    doc.fillColor(GREEN).fontSize(8.5).font('Helvetica-Bold')
      .text('CREDIT HOURS RECOMMENDED FOR APPROVAL',
        MARGIN + 4, y + 4, { width: SC[0]+SC[1]+SC[2]+SC[3]-8, lineBreak: false })
      .text(String(approvedTotal),
        MARGIN + SC[0]+SC[1]+SC[2]+SC[3] + 4, y + 4, { width: SC[4], lineBreak: false });
    y += 17;

    // Declaration box
    y = ensureSpace(doc, y, 90);
    y += 18;
    doc.rect(MARGIN, y, USABLE_W, 70).strokeColor('#aaaaaa').lineWidth(0.75).stroke();
    doc.fillColor(GREY_MID).fontSize(8.5).font('Helvetica')
      .text(
        'DECLARATION: This report has been generated by Credit Path AI ' +
        'using automated syllabus matching and AI-assisted topic analysis. The results herein are ' +
        'recommendations only and are subject to final review and approval by the responsible academic ' +
        'lecturer or committee. Approved credits will be recorded in the student\'s academic transcript ' +
        'upon official endorsement.',
        MARGIN + 10, y + 10, { width: USABLE_W - 20 }
      );

    // Footer on the last page
    drawFooter(doc);
    doc.end();

  } catch (err) {
    log.error({ module: MODULE, fn, analysisId, err }, 'Failed to generate report');
    if (!res.headersSent) res.status(500).json({ error: { code: 'REPORT_ERROR', message: err.message } });
  }
}
