import { log } from '../utils/logger.js';

const MODULE = 'syllabusParser';

/**
 * Parse plain text from a mock diploma syllabus PDF.
 * Handles the attribute:value + list format generated by generateMockPdfs.js.
 * @param {string} text
 * @returns {{ ok: boolean, data?: object, error?: string }}
 */
export function parseSyllabusText(text) {
  const fn = 'parseSyllabusText';
  try {
    log.info({ module: MODULE, fn }, 'Parsing syllabus text');

    const lines = text.split('\n').map(l => l.trim()).filter(Boolean);

    const get = (key) => {
      const line = lines.find(l => l.toUpperCase().startsWith(key.toUpperCase() + ':'));
      return line ? line.slice(key.length + 1).trim() : null;
    };

    const subjectCode = get('SUBJECT CODE');
    const subjectName = get('SUBJECT NAME');
    const institution = get('INSTITUTION');
    const programme = get('PROGRAMME');
    const creditStr = get('CREDIT');
    const credit = creditStr ? parseInt(creditStr, 10) : null;
    const prerequisites = get('PREREQUISITES');

    // Extract TOPICS COVERED section
    const topics = extractListSection(lines, 'TOPICS COVERED');
    const references = extractListSection(lines, 'REFERENCES');

    // Extract SYNOPSIS section (multi-line paragraph)
    const synopsis = extractParagraph(lines, 'SYNOPSIS');

    if (!subjectCode) {
      return { ok: false, error: 'Could not find SUBJECT CODE in PDF text' };
    }

    const result = { subject_code: subjectCode, subject_name: subjectName, institution, programme, credit, synopsis, topics, references, prerequisites };
    log.info({ module: MODULE, fn, subjectCode, topicCount: topics.length }, 'Syllabus parsed');
    return { ok: true, data: result };
  } catch (err) {
    log.error({ module: MODULE, fn, err }, 'Failed to parse syllabus');
    return { ok: false, error: err.message };
  }
}

/**
 * Extract a bulleted list section from lines following a section header.
 * @param {string[]} lines
 * @param {string} sectionHeader
 * @returns {string[]}
 */
function extractListSection(lines, sectionHeader) {
  const headerIdx = lines.findIndex(l => l.toUpperCase().startsWith(sectionHeader.toUpperCase()));
  if (headerIdx === -1) return [];

  const items = [];
  for (let i = headerIdx + 1; i < lines.length; i++) {
    const line = lines[i];
    // Stop at next section header (all caps label ending with colon)
    if (/^[A-Z][A-Z\s]+:/.test(line) && !line.startsWith('-')) break;
    if (line.startsWith('-')) {
      items.push(line.slice(1).trim());
    }
  }
  return items;
}

/**
 * Extract a paragraph section from lines following a section header.
 * @param {string[]} lines
 * @param {string} sectionHeader
 * @returns {string}
 */
function extractParagraph(lines, sectionHeader) {
  const headerIdx = lines.findIndex(l => l.toUpperCase().startsWith(sectionHeader.toUpperCase()));
  if (headerIdx === -1) return '';

  const parts = [];
  for (let i = headerIdx + 1; i < lines.length; i++) {
    const line = lines[i];
    if (/^[A-Z][A-Z\s]+:/.test(line)) break;
    if (!line.startsWith('-')) parts.push(line);
  }
  return parts.join(' ').trim();
}
