import { log } from '../utils/logger.js';

const MODULE = 'transcriptParser';

/**
 * Parse plain text extracted from a mock transcript PDF.
 * Handles the attribute:value + table format generated by generateMockPdfs.js.
 * @param {string} text
 * @returns {{ ok: boolean, data?: object, error?: string }}
 */
export function parseTranscriptText(text) {
  const fn = 'parseTranscriptText';
  try {
    log.info({ module: MODULE, fn }, 'Parsing transcript text');

    const lines = text.split('\n').map(l => l.trim()).filter(Boolean);

    const get = (key) => {
      const line = lines.find(l => l.toUpperCase().startsWith(key + ':'));
      return line ? line.slice(key.length + 1).trim() : null;
    };

    const studentName = get('STUDENT NAME');
    const regNo = get('REGISTRATION NO');
    const cgpaStr = get('CUMULATIVE GPA') || get('CGPA');
    const cgpa = cgpaStr ? parseFloat(cgpaStr) : null;
    const institution = get('INSTITUTION');
    const programme = get('PROGRAMME');

    const semesters = [];
    let currentSemester = null;
    let inTable = false;

    for (const line of lines) {
      // Detect semester headers like "SEMESTER 1:" or "SEMESTER 1"
      const semMatch = line.match(/^(SEMESTER\s+\d+)/i);
      if (semMatch) {
        currentSemester = { semester: semMatch[1], entries: [] };
        semesters.push(currentSemester);
        inTable = false;
        continue;
      }

      // Detect table header row
      if (line.includes('SUBJECT CODE') && line.includes('GRADE')) {
        inTable = true;
        continue;
      }

      // Skip separator lines
      if (/^[-|]+$/.test(line.replace(/\s/g, ''))) continue;

      // Parse table rows: CODE | NAME | CREDIT | GRADE
      if (inTable && currentSemester && line.includes('|')) {
        const parts = line.split('|').map(p => p.trim());
        if (parts.length >= 4) {
          const subjectCode = parts[0].trim();
          const subjectName = parts[1].trim();
          const credit = parseInt(parts[2], 10);
          const grade = parts[3].trim();
          if (subjectCode && grade && !isNaN(credit)) {
            currentSemester.entries.push({ subject_code: subjectCode, subject_name: subjectName, credit, grade });
          }
        }
      }
    }

    const result = { student_name: studentName, reg_no: regNo, cgpa, institution, programme, semesters };
    log.info({ module: MODULE, fn, semesterCount: semesters.length, entryCount: semesters.reduce((s, sem) => s + sem.entries.length, 0) }, 'Transcript parsed');
    return { ok: true, data: result };
  } catch (err) {
    log.error({ module: MODULE, fn, err }, 'Failed to parse transcript');
    return { ok: false, error: err.message };
  }
}
